Using the two newest finer grid data, compare on a point-by-point basis the scaling between stronger and weaker fields. For now, should get constant difference (or scaling?) at all points.

## Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import pandas as pd
import pickle as pkl
from datetime import datetime
from dateutil import parser

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib inline
plt.rcParams['figure.figsize'] = (12.0, 8.0)
plt.rcParams['axes.axisbelow'] = True

from plotly.offline import init_notebook_mode, plot, iplot
import plotly.graph_objs as go
import plotly.io as pio
init_notebook_mode(True)

from hallprobecalib import hpc_ext_path
from hallprobecalib.hpcplots import scatter2d,scatter3d,histo

## Cleaning/Matching Data

In [4]:
plotdir = hpc_ext_path+'plots/magnet_maps/Comparison_Strengths_01/'

In [5]:
directory = hpc_ext_path+'datafiles/magnet_maps/'
filename_weak = '2019-05-24 074557.pkl'
filename_strong = '2019-06-06 133226.pkl'

In [7]:
df_weak = pkl.load(open(directory+filename_weak,'rb'))
df_strong = pkl.load(open(directory+filename_strong,'rb'))

In [11]:
df_weak.describe()

Magnet Current [V]   Magnet Voltage [V]       NMR [T]  \
count         17576.000000         17576.000000  17576.000000   
mean              8.943584            40.638967      1.037618   
std               0.000015             0.077918      0.566943   
min               8.943555            40.390533      0.000000   
25%               8.943573            40.584346      1.346835   
50%               8.943581            40.633567      1.347349   
75%               8.943595            40.707187      1.347622   
max               8.943623            40.748850      1.348617   

        Zaber_Pattern_X   Zaber_Pattern_Y   Zaber_Pattern_Z  \
count      17576.000000      17576.000000      1.757600e+04   
mean      552000.000000     452000.000000      1.620000e+06   
std        30000.853473      30000.853473      3.000085e+04   
min       502000.000000     402000.000000      1.570000e+06   
25%       526000.000000     426000.000000      1.594000e+06   
50%       552000.000000     452000.000000      1.620000e+06   
75%       578000.000000     478000.000000      1.646000e+06   
max       602000.000000     502000.000000      1.670000e+06   

        Zaber_Meas_Encoder_X   Zaber_Meas_Encoder_Y   Zaber_Meas_Encoder_Z  \
count           17576.000000           17576.000000           17576.000000   
mean           215625.000000          176562.500000          632812.500000   
std             11719.083388           11719.083388           11719.083388   
min            196093.750000          157031.250000          613281.250000   
25%            205468.750000          166406.250000          622656.250000   
50%            215625.000000          176562.500000          632812.500000   
75%            225781.250000          186718.750000          642968.750000   
max            235156.250000          196093.750000          652343.750000   

           GRAD_B_X      GRAD_B_Y      GRAD_B_Z    GRAD_B_MAG  
count  1.757600e+04  1.757600e+04  1.757600e+04  1.757600e+04  
mean  -2.393625e-07  2.516702e-06  1.234399e-05  1.830754e-05  
std    2.780704e-05  3.476070e-05  4.664143e-05  6.309160e-05  
min   -3.370935e-04 -3.370038e-04 -3.370501e-04  0.000000e+00  
25%   -2.025750e-09 -2.676375e-09 -8.723125e-10  8.996971e-09  
50%    9.131250e-10  0.000000e+00  8.375000e-11  1.868761e-08  
75%    2.153838e-08  6.149656e-09  6.209625e-09  2.819744e-08  
max    3.371318e-04  3.371478e-04  3.366864e-04  5.056852e-04

In [10]:
df_strong.describe()

Magnet Current [V]   Magnet Voltage [V]       NMR [T]  \
count         17576.000000         17576.000000  17576.000000   
mean              8.472852            38.442974      1.097418   
std               0.000008             0.045520      0.492796   
min               8.472832            38.264517      0.000000   
25%               8.472846            38.412883      1.318363   
50%               8.472853            38.456583      1.318658   
75%               8.472857            38.479617      1.318915   
max               8.472875            38.520350      1.319720   

        Zaber_Pattern_X   Zaber_Pattern_Y   Zaber_Pattern_Z  \
count      17576.000000      17576.000000      1.757600e+04   
mean      550000.000000     450000.000000      1.620000e+06   
std        30000.853473      30000.853473      3.000085e+04   
min       500000.000000     400000.000000      1.570000e+06   
25%       524000.000000     424000.000000      1.594000e+06   
50%       550000.000000     450000.000000      1.620000e+06   
75%       576000.000000     476000.000000      1.646000e+06   
max       600000.000000     500000.000000      1.670000e+06   

        Zaber_Meas_Encoder_X   Zaber_Meas_Encoder_Y   Zaber_Meas_Encoder_Z  \
count           17576.000000           17576.000000           17576.000000   
mean           214843.750000          175781.250000          632812.500000   
std             11719.083388           11719.083388           11719.083388   
min            195312.500000          156250.000000          613281.250000   
25%            204687.500000          165625.000000          622656.250000   
50%            214843.750000          175781.250000          632812.500000   
75%            225000.000000          185937.500000          642968.750000   
max            234375.000000          195312.500000          652343.750000   

           GRAD_B_X      GRAD_B_Y      GRAD_B_Z    GRAD_B_MAG  
count  1.757600e+04  1.757600e+04  1.757600e+04  1.757600e+04  
mean   6.303692e-07  1.905080e-06  1.255986e-05  1.674130e-05  
std    2.579530e-05  3.114969e-05  4.487310e-05  5.942049e-05  
min   -1.648766e-04 -3.298107e-04 -3.298243e-04  0.000000e+00  
25%   -4.210688e-09 -2.621000e-09 -8.930313e-10  1.054214e-08  
50%    1.415563e-09  0.000000e+00  7.696875e-10  1.945319e-08  
75%    2.180594e-08  6.124219e-09  6.962188e-09  2.711804e-08  
max    3.299127e-04  3.299129e-04  3.295322e-04  4.947447e-04

In [18]:
df_w = df_weak[df_weak['NMR [T]'] != 0]
df_s = df_strong[df_strong['NMR [T]'] != 0]

In [19]:
nw = df_w["NMR [T]"] > df_w["NMR [T]"].quantile(0.02)
ns= df_s["NMR [T]"] > df_s["NMR [T]"].quantile(0.02)

In [20]:
histo(df_w[nw]['NMR [T]'],bins=25,inline=True);
histo(df_s[ns]['NMR [T]'],bins=25,inline=True);

In [26]:
xw = df_weak[' Zaber_Pattern_X'].unique()
xs = df_strong[' Zaber_Pattern_X'].unique()

In [27]:
xw

array([502000., 506000., 510000., 514000., 518000., 522000., 526000.,
       530000., 534000., 538000., 542000., 546000., 550000., 554000.,
       558000., 562000., 566000., 570000., 574000., 578000., 582000.,
       586000., 590000., 594000., 598000., 602000.])

In [28]:
xs

array([500000., 504000., 508000., 512000., 516000., 520000., 524000.,
       528000., 532000., 536000., 540000., 544000., 548000., 552000.,
       556000., 560000., 564000., 568000., 572000., 576000., 580000.,
       584000., 588000., 592000., 596000., 600000.])

In [25]:
yw = df_weak[' Zaber_Pattern_Y'].unique()
ys = df_strong[' Zaber_Pattern_Y'].unique()

In [30]:
yw

array([402000., 406000., 410000., 414000., 418000., 422000., 426000.,
       430000., 434000., 438000., 442000., 446000., 450000., 454000.,
       458000., 462000., 466000., 470000., 474000., 478000., 482000.,
       486000., 490000., 494000., 498000., 502000.])

In [31]:
ys

array([400000., 404000., 408000., 412000., 416000., 420000., 424000.,
       428000., 432000., 436000., 440000., 444000., 448000., 452000.,
       456000., 460000., 464000., 468000., 472000., 476000., 480000.,
       484000., 488000., 492000., 496000., 500000.])

In [29]:
zw = df_weak[' Zaber_Pattern_Z'].unique()
zs = df_strong[' Zaber_Pattern_Z'].unique()

In [32]:
zw

array([1570000., 1574000., 1578000., 1582000., 1586000., 1590000.,
       1594000., 1598000., 1602000., 1606000., 1610000., 1614000.,
       1618000., 1622000., 1626000., 1630000., 1634000., 1638000.,
       1642000., 1646000., 1650000., 1654000., 1658000., 1662000.,
       1666000., 1670000.])

In [33]:
zs

array([1570000., 1574000., 1578000., 1582000., 1586000., 1590000.,
       1594000., 1598000., 1602000., 1606000., 1610000., 1614000.,
       1618000., 1622000., 1626000., 1630000., 1634000., 1638000.,
       1642000., 1646000., 1650000., 1654000., 1658000., 1662000.,
       1666000., 1670000.])

So x and y coordinates have shift of 20000...will have to interpolate, or something like that.

Idea to think about: run map exactly same coordinates as one of these maps, but at half the field (maybe not useful due to Mu2e magnetic field)
- Also do this for a much coarser map to get an overall picture.